name: quick_cab
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  eva_icons_flutter: ^3.1.0
  intl: ^0.17.0
  timelines: ^0.1.0
  bottom_navy_bar: ^6.0.0
  backdrop: ^0.7.1
  google_maps_flutter: ^2.1.3
  geocode: ^1.0.1
  shimmer: ^2.0.0
  flutter_credit_card: ^3.0.1
  country_code_picker: ^2.0.2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/intro.png
    - assets/avatar.png
    - assets/promotion_model.png
    - assets/map.png
    - assets/rick.jpg
    - assets/launcher.png
